/// ข้อความ UI 3 ภาษา (คำทำนายมาจาก API แล้ว — ที่นี่แค่ป้าย UI)
const Map<String, Map<String, String>> S = {
  "th": {
    "title": "Number Luck",
    "tagline": "ทำนายเบอร์พม่า · พม่า+จีน+อินเดีย",
    "phone": "เบอร์โทรศัพท์ (09XXXXXXXXX)",
    "birthday": "วันเกิด (ไม่บังคับ — เพื่อเช็คดวง)",
    "analyze": "🔮 ทำนายเบอร์",
    "grade": "เกรด",
    "premium": "⭐ เบอร์พรีเมียม (เกิน 97)",
    "pairs": "โครงสร้างคู่เลข",
    "readings": "คำทำนายโชคชะตา",
    "sum": "ผลรวมเบอร์",
    "compat": "ความเข้ากันกับวันเกิด",
    "weekly": "ดวงสัปดาห์นี้",
    "lucky": "เลขนำโชค",
    "loading": "กำลังทำนาย…",
    "error": "เกิดข้อผิดพลาด ลองใหม่อีกครั้ง",
    "bad_number": "เบอร์ไม่ถูกต้อง — 09 ตามด้วย 7-9 หลัก",
    "pick_date": "เลือกวันเกิด",
    "no_date": "ยังไม่เลือก",
  },
  "en": {
    "title": "Number Luck",
    "tagline": "Myanmar number reading · MM+CN+IN",
    "phone": "Phone number (09XXXXXXXXX)",
    "birthday": "Birthday (optional — for compatibility)",
    "analyze": "🔮 Analyze",
    "grade": "Grade",
    "premium": "⭐ Premium number (above 97)",
    "pairs": "Digit-pair structure",
    "readings": "Fortune reading",
    "sum": "Number sum",
    "compat": "Birthday compatibility",
    "weekly": "This week",
    "lucky": "Lucky numbers",
    "loading": "Reading…",
    "error": "Something went wrong. Try again.",
    "bad_number": "Invalid number — 09 then 7-9 digits",
    "pick_date": "Pick birthday",
    "no_date": "Not set",
  },
  "mm": {
    "title": "Number Luck",
    "tagline": "မြန်မာဖုန်းဗေဒင် · မြန်မာ+တရုတ်+အိန္ဒိယ",
    "phone": "ဖုန်းနံပါတ် (09XXXXXXXXX)",
    "birthday": "မွေးနေ့ (မဖြစ်မနေမဟုတ် — ကိုက်ညီမှုစစ်ရန်)",
    "analyze": "🔮 ဗေဒင်ကြည့်မည်",
    "grade": "အဆင့်",
    "premium": "⭐ ပရီမီယံနံပါတ် (၉၇ ကျော်)",
    "pairs": "ဂဏန်းတွဲဖွဲ့စည်းပုံ",
    "readings": "ကံကြမ္မာဟောစာတမ်း",
    "sum": "ဂဏန်းပေါင်းလဒ်",
    "compat": "မွေးနေ့နှင့်ကိုက်ညီမှု",
    "weekly": "ဤအပတ်",
    "lucky": "ကံကောင်းဂဏန်း",
    "loading": "ဗေဒင်ကြည့်နေသည်…",
    "error": "အမှားဖြစ်သည်။ ထပ်စမ်းပါ။",
    "bad_number": "နံပါတ်မမှန် — 09 နောက် ၇-၉ လုံး",
    "pick_date": "မွေးနေ့ရွေးပါ",
    "no_date": "မရွေးရသေး",
  },
};

String t(String lang, String key) => S[lang]?[key] ?? S["en"]![key] ?? key;
