name: number_luck
description: Number Luck — Myanmar phone number fortune (Thai/English/Burmese)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.0    # เก็บภาษา/วันเกิดในเครื่อง
  intl: ^0.19.0

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
